# Generated by Django 5.1.7 on 2025-03-23 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdocument',
            name='user_id',
            field=models.IntegerField(default=-1),
        ),
    ]
